name: Homebrew tap

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-26
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: brew test-bot --only-tap-syntax
